"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        // Sidebar
        'nav.ops': 'Unified Operations',
        'nav.dashboard': 'Dashboard',
        'nav.taskPortal': 'Task Portal',
        'nav.projects': 'Projects',
        'nav.crm': 'Customer CRM',
        'nav.erp': 'ERP System',
        'nav.resources': 'Resources',
        'nav.schedules': 'Schedules',
        'nav.consultants': 'Consultants',
        'nav.assets': 'Client Assets',
        'nav.facility': 'Facility Allocation',
        'nav.financial': 'Financial Hub',
        'nav.opsReports': 'Ops Reports',
        'nav.departments': 'Departments',
        'nav.portals': 'Portals',
        'nav.clientPortal': 'Client Portal',
        'nav.collaborator': 'Collaborator',

        // Projects Module
        'projects.title': 'Project Ecosystem',
        'projects.subtitle': 'Lifecycle tracking and strategic resource alignment.',
        'projects.new': '+ Define Project',
        'projects.view.overview': 'Overview',
        'projects.view.board': 'Project Board',
        'projects.view.timeline': 'Timeline',
        'projects.status.active': 'Active',
        'projects.status.planning': 'Planning',
        'projects.status.completed': 'Completed',
        'projects.risk.low': 'Stable',
        'projects.risk.medium': 'At Risk',
        'projects.risk.high': 'Critical',
        'projects.manager': 'Lead',
        'projects.progress': 'Completion',

        // Board Table Headers
        'projects.board.item': 'Element',
        'projects.board.responsible': 'Responsible',
        'projects.board.project': 'Project',
        'projects.board.priority': 'Priority',
        'projects.board.status': 'Status',
        'projects.board.startDate': 'Start Date',
        'projects.board.deadline': 'Delivery Date',
        'projects.board.progress': 'Progress',
        'projects.board.thisWeek': 'THIS WEEK',
        'projects.board.nextWeek': 'NEXT WEEK',
        'projects.board.done': 'DONE',
        'projects.board.newTagPrompt': 'Enter the name for the new tag:',
        'projects.board.editTags': 'Edit Tags',
        'projects.board.autoAssign': 'Auto-assign tags',

        // New Menu Groups
        'nav.management': 'Management',
        'nav.marketing': 'Marketing',
        'nav.communication': 'Communication',

        // Management Items
        'nav.growth': 'Growth Stats',
        'nav.inventory': 'Inventory',
        'nav.purchases': 'Purchases',
        'nav.surveys': 'Surveys',
        'nav.pipeline': 'Client Pipeline',
        'nav.team': 'Team',
        'nav.portfolio': 'Portfolio',
        'nav.sales': 'Sales',

        // Marketing Items
        'nav.outreach': 'Outreach',
        'nav.emailMarketing': 'Email Marketing',
        'nav.smsMarketing': 'SMS Marketing',
        'nav.marketingAutomation': 'Marketing Automation',
        'nav.socialMedia': 'Social Media',
        'nav.events': 'Events',

        // Communication Items
        'nav.conversations': 'Conversations',
        'nav.contracts': 'Contracts',
        'nav.scheduling': 'Scheduling',

        // TopNav
        'top.search': 'Search anything...',
        'top.role': 'Super Admin',

        // Dashboard
        'dash.title': 'BLC Operations Hub',
        'dash.subtitle': 'Unified Management & Operations Hub.',
        'dash.stats.tasks': 'Active Tasks',
        'dash.stats.clients': 'New Clients',
        'dash.stats.projects': 'Ops Projects',
        'dash.stats.consultants': 'Consultants',
        'dash.stats.specialists': 'Risk & Anomaly Alerts',
        'dash.stats.staff': 'AI Agents Staff',
        'dash.stats.revenue': 'Revenue Hub',
        'dash.stats.yesterday': 'Yesterday',
        'dash.stats.today': 'Today Active',
        'dash.stats.todayAvail': 'Today Available',
        'dash.stats.growth': 'Global Growth',
        'dash.stats.inventoryVal': 'Inventory Value',
        'dash.stats.activePipeline': 'Active Pipeline',
        'dash.pillar.management': 'Management Intelligence',
        'dash.pillar.marketing': 'Marketing & Growth',
        'dash.pillar.communication': 'Unified Communication',
        'dash.export': 'Export Report',
        'dash.newTask': '+ New Task',
        'dash.featured': 'Active Task Resume',
        'dash.activeTasks': 'Active Tasks',
        'dash.upcoming': 'Upcoming to Expire',
        'dash.task1': 'Security Audit Report',
        'dash.task2': 'Client Infrastructure Sync',
        'dash.task3': 'Financial Quarter Review',
        'dash.task4': 'Network Optimization',
        'dash.task5': 'User Access Audit',
        'dash.due': 'Due',
        'dash.upcomingMeetings': 'Upcoming Meetings',
        'dash.meet1': 'Client Sync',
        'dash.meet2': 'Ops Review',
        'dash.meet3': 'Strategy Call',
        'dash.at': 'at',
        'modal.title': 'Create New Task',
        'modal.taskTitle': 'Task Title',
        'modal.taskPlaceholder': 'e.g. Scrape financial data',
        'modal.description': 'Description',
        'modal.descPlaceholder': 'Provide details about the task...',
        'modal.priority': 'Priority',
        'modal.collaborator': 'Collaborator',
        'modal.collPlaceholder': 'Assignee name',
        'modal.cancel': 'Cancel',
        'modal.create': 'Create Task',
        'dash.fromBLC': 'From: BLC Main Operations',
        'dash.leadRole': 'Exec. Operations Lead',
        'dash.oversight': 'Management Oversight',
        'dash.leadDesc': 'Responsible for driving operational excellence and ensuring project delivery timelines. Oversees the integration of the BLC hub across all departments.',
        'dash.efficiency': 'Efficiency',
        'dash.projectsCount': 'Projects',
        'dash.productivity': 'Productivity Trends',
        'dash.focusHours': 'Daily Focus hours',
        'dash.loggedWeek': 'logged this week',
        'dash.vsLastWeek': 'vs last week',
        'dash.weekView': 'Week',
        'dash.calendar': 'Calendar',
        'dash.calendar.su': 'Su',
        'dash.calendar.mo': 'Mo',
        'dash.calendar.tu': 'Tu',
        'dash.calendar.we': 'We',
        'dash.calendar.th': 'Th',
        'dash.calendar.fr': 'Fr',
        'dash.calendar.sa': 'Sa',

        // CRM
        'crm.title': 'Client CRM Center',
        'crm.subtitle': 'Relationship management and asset pipeline.',
        'crm.newContact': '+ New Contact',
        'crm.activeClients': 'Active Clients',
        'crm.newLeads': 'New Leads',
        'crm.conversion': 'Conversion Rate',
        'crm.recent': 'Recent Contacts',
        'crm.viewAll': 'View All →',
        'crm.status.lead': 'Lead',
        'crm.status.active': 'Active',
        'crm.status.churned': 'Inactive',
        'crm.lastContact': 'Last contact',

        // ERP
        'erp.title': 'ERP & Finance Center',
        'erp.subtitle': 'Resource management and financial oversight.',
        'erp.revenue': 'Total Revenue (YTD)',
        'erp.burn': 'Monthly Burn Rate',
        'erp.utilization': 'Resource Utilization',
        'erp.invoices': 'Outstanding Invoices',
        'erp.distribution': 'Financial Distribution',
        'erp.infrastructure': 'Infrastructure',
        'erp.salaries': 'Salaries & Talent',
        'erp.marketing': 'Marketing',
        'erp.reserve': 'Reserve Fund',
        'erp.allocation': 'Resource Allocation',

        // Tasks
        'tasks.title': 'Task Platform',
        'tasks.subtitle': 'Operational workflow management and tracking.',
        'tasks.create': '+ Create Task',
        'tasks.all': 'All',
        'tasks.todo': 'Todo',
        'tasks.inProgress': 'In Progress',
        'tasks.completed': 'Completed',
        'tasks.column.todo': 'To Do',
        'tasks.column.progress': 'In Progress',
        'tasks.priority.high': 'High',
        'tasks.priority.medium': 'Medium',
        'tasks.priority.low': 'Low',
        'tasks.details': 'Details',
        'tasks.view.main': 'Main',
        'tasks.view.gantt': 'Gantt',
        'tasks.view.milestone': 'Milestones',
        'tasks.view.kanban': 'Kanban',
        'tasks.view.tracking': 'Time Tracking',
        'tasks.view.main.desc': 'Overall project status, tasks, and key metrics.',
        'tasks.view.gantt.desc': 'Visualize duration, dependencies, and task progress.',
        'tasks.view.kanban.desc': 'Organize tasks by status: Todo, In Progress, and Completed.',
        'tasks.view.milestone.desc': 'Track critical deliverables and major milestones.',
        'tasks.view.tracking.desc': 'Check time spent per task and assignee.',
        'tasks.tracking.upcomingActivity': 'Upcoming Activity',
        'tasks.tracking.upcomingSchedule': 'Upcoming Schedule',
        'tasks.tracking.seeAll': 'See All Activity',
        'tasks.tracking.workingOn': 'Working On',
        'tasks.days.mon': 'Mon',
        'tasks.days.tue': 'Tue',
        'tasks.days.wed': 'Wed',
        'tasks.days.thu': 'Thu',
        'tasks.days.fri': 'Fri',
        'tasks.days.sat': 'Sat',
        'tasks.days.sun': 'Sun',
        'tasks.field.assignee': 'Assignee',
        'tasks.field.duration': 'Duration',
        'tasks.field.start': 'Start Date',
        'tasks.field.end': 'End Date',
        'tasks.field.progress': 'Progress',
    },
    es: {
        // Sidebar
        'nav.ops': 'Operaciones Unificadas',
        'nav.dashboard': 'Panel de Control',
        'nav.taskPortal': 'Portal de Tareas',
        'nav.projects': 'Proyectos',
        'nav.crm': 'Gestión CRM',
        'nav.erp': 'Centro ERP',
        'nav.resources': 'Recursos',
        'nav.schedules': 'Calendarios',
        'nav.consultants': 'Consultores',
        'nav.assets': 'Activos de Clientes',
        'nav.facility': 'Asignación de Instalaciones',
        'nav.financial': 'Centro Financiero',
        'nav.opsReports': 'Informes Ops',
        'nav.departments': 'Departamentos',
        'nav.portals': 'Portales',
        'nav.clientPortal': 'Portal de Clientes',
        'nav.collaborator': 'Colaborador',

        // Projects Module
        'projects.title': 'Ecosistema de Proyectos',
        'projects.subtitle': 'Seguimiento del ciclo de vida y alineación estratégica de recursos.',
        'projects.new': '+ Definir Proyecto',
        'projects.view.overview': 'Vista General',
        'projects.view.board': 'Tablero de Proyecto',
        'projects.view.timeline': 'Línea de Tiempo',
        'projects.status.active': 'Activo',
        'projects.status.planning': 'Planificación',
        'projects.status.completed': 'Completado',
        'projects.risk.low': 'Estable',
        'projects.risk.medium': 'En Riesgo',
        'projects.risk.high': 'Crítico',
        'projects.manager': 'Responsable',
        'projects.progress': 'Progreso',

        // Board Table Headers
        'projects.board.item': 'Elemento',
        'projects.board.responsible': 'Responsable',
        'projects.board.project': 'Proyecto',
        'projects.board.priority': 'Prioridad',
        'projects.board.status': 'Estado',
        'projects.board.startDate': 'Fecha de Inicio',
        'projects.board.deadline': 'Fecha de Entrega',
        'projects.board.progress': 'Progreso',
        'projects.board.thisWeek': 'ESTA SEMANA',
        'projects.board.nextWeek': 'LA PROXIMA SEMANA',
        'projects.board.done': 'LISTO',
        'projects.board.newTagPrompt': 'Ingrese el nombre de la nueva etiqueta:',
        'projects.board.editTags': 'Editar etiquetas',
        'projects.board.autoAssign': 'Autoasignar etiquetas',

        // New Menu Groups
        'nav.management': 'Gestión Administrativa',
        'nav.marketing': 'Marketing & CRM',
        'nav.communication': 'Comunicación',

        // Management Items
        'nav.growth': 'Estadísticas de Crecimiento',
        'nav.inventory': 'Inventario',
        'nav.purchases': 'Compras',
        'nav.surveys': 'Encuestas',
        'nav.pipeline': 'Pipeline de Clientes',
        'nav.team': 'Equipo',
        'nav.portfolio': 'Portafolio',
        'nav.sales': 'Ventas',

        // Marketing Items
        'nav.outreach': 'Prospección (Outreach)',
        'nav.emailMarketing': 'Email Marketing',
        'nav.smsMarketing': 'SMS Marketing',
        'nav.marketingAutomation': 'Automatización Marketing',
        'nav.socialMedia': 'Redes Sociales',
        'nav.events': 'Eventos',

        // Communication Items
        'nav.conversations': 'Conversaciones',
        'nav.contracts': 'Contratos',
        'nav.scheduling': 'Agenda & Citas',

        // TopNav
        'top.search': 'Buscar todo...',
        'top.role': 'Panel Senior',

        // Dashboard
        'dash.title': 'Panel de Operaciones BLC',
        'dash.subtitle': 'Centro de Gestión y Operaciones Unificadas.',
        'dash.stats.tasks': 'Tareas Activas',
        'dash.stats.clients': 'Nuevos Clientes',
        'dash.stats.projects': 'Proyectos Ops',
        'dash.stats.consultants': 'Consultores',
        'dash.stats.specialists': 'Alertas de Riesgo y Anomalía',
        'dash.stats.staff': 'Personal de Agentes IA',
        'dash.stats.revenue': 'Centro de Ingresos',
        'dash.stats.yesterday': 'Ayer',
        'dash.stats.today': 'Activos Hoy',
        'dash.stats.todayAvail': 'Disponibles Hoy',
        'dash.stats.growth': 'Crecimiento Global',
        'dash.stats.inventoryVal': 'Valor de Inventario',
        'dash.stats.activePipeline': 'Pipeline Activo',
        'dash.pillar.management': 'Inteligencia de Gestión',
        'dash.pillar.marketing': 'Marketing y Crecimiento',
        'dash.pillar.communication': 'Comunicación Unificada',
        'dash.export': 'Exportar Informe',
        'dash.newTask': '+ Nueva Tarea',
        'dash.featured': 'Resumen de Tareas Activas',
        'dash.activeTasks': 'Tareas Activas',
        'dash.upcoming': 'Próximas a Vencer',
        'dash.task1': 'Informe de Auditoría de Seguridad',
        'dash.task2': 'Sincronización de Infraestructura',
        'dash.task3': 'Revisión Trimestral Financiera',
        'dash.task4': 'Optimización de Red',
        'dash.task5': 'Auditoría de Accesos',
        'dash.due': 'Vence',
        'dash.upcomingMeetings': 'Próximas Reuniones',
        'dash.meet1': 'Sincronización Cliente',
        'dash.meet2': 'Revisión Operaciones',
        'dash.meet3': 'Llamada Estrategia',
        'dash.at': 'a las',
        'modal.title': 'Crear Nueva Tarea',
        'modal.taskTitle': 'Título de la Tarea',
        'modal.taskPlaceholder': 'ej. Extraer datos financieros',
        'modal.description': 'Descripción',
        'modal.descPlaceholder': 'Proporciona detalles sobre la tarea...',
        'modal.priority': 'Prioridad',
        'modal.collaborator': 'Colaborador',
        'modal.collPlaceholder': 'Nombre del responsable',
        'modal.cancel': 'Cancelar',
        'modal.create': 'Crear Tarea',
        'dash.fromBLC': 'De: Operaciones Principales BLC',
        'dash.leadRole': 'Líder Ejecutivo de Ops',
        'dash.oversight': 'Supervisión de Gestión',
        'dash.leadDesc': 'Responsable de optimizar el rendimiento operativo y asegurar la entrega de proyectos a tiempo. Supervisa la integración del hub BLC en todos los departamentos.',
        'dash.efficiency': 'Eficiencia',
        'dash.projectsCount': 'Proyectos',
        'dash.productivity': 'Tendencias de Productividad',
        'dash.focusHours': 'Horas de enfoque diarias',
        'dash.loggedWeek': 'registradas esta semana',
        'dash.vsLastWeek': 'vs la semana pasada',
        'dash.weekView': 'Semana',
        'dash.calendar': 'Calendario',
        'dash.calendar.su': 'Do',
        'dash.calendar.mo': 'Lu',
        'dash.calendar.tu': 'Ma',
        'dash.calendar.we': 'Mi',
        'dash.calendar.th': 'Ju',
        'dash.calendar.fr': 'Vi',
        'dash.calendar.sa': 'Sá',

        // CRM
        'crm.title': 'Centro de Clientes CRM',
        'crm.subtitle': 'Gestión de relaciones y pipeline de activos.',
        'crm.newContact': '+ Nuevo Contacto',
        'crm.activeClients': 'Clientes Activos',
        'crm.newLeads': 'Nuevos Leads',
        'crm.conversion': 'Tasa de Conversión',
        'crm.recent': 'Contactos Recientes',
        'crm.viewAll': 'Ver Todos →',
        'crm.status.lead': 'Potencial',
        'crm.status.active': 'Activo',
        'crm.status.churned': 'Inactivo',
        'crm.lastContact': 'Último contacto',

        // ERP
        'erp.title': 'Centro ERP y Finanzas',
        'erp.subtitle': 'Gestión de recursos y supervisión financiera.',
        'erp.revenue': 'Ingresos Totales (YTD)',
        'erp.burn': 'Gasto Mensual',
        'erp.utilization': 'Uso de Recursos',
        'erp.invoices': 'Facturas Pendientes',
        'erp.distribution': 'Distribución Financiera',
        'erp.infrastructure': 'Infraestructura',
        'erp.salaries': 'Salarios y Talento',
        'erp.marketing': 'Marketing',
        'erp.reserve': 'Fondo de Reserva',
        'erp.allocation': 'Asignación de Recursos',

        // Tasks
        'tasks.title': 'Plataforma de Tareas',
        'tasks.subtitle': 'Gestión de flujos de trabajo operativos y seguimiento.',
        'tasks.create': '+ Crear Tarea',
        'tasks.all': 'Todas',
        'tasks.todo': 'Pendientes',
        'tasks.inProgress': 'En Proceso',
        'tasks.completed': 'Completadas',
        'tasks.column.todo': 'Por Hacer',
        'tasks.column.progress': 'En Proceso',
        'tasks.priority.high': 'Alta',
        'tasks.priority.medium': 'Media',
        'tasks.priority.low': 'Baja',
        'tasks.details': 'Detalles',
        'tasks.view.main': 'Inicio',
        'tasks.view.gantt': 'Gantt',
        'tasks.view.milestone': 'Hitos',
        'tasks.view.kanban': 'Kanban',
        'tasks.view.tracking': 'Time Tracking',
        'tasks.view.main.desc': 'Resumen del estado del proyecto, tareas y métricas clave.',
        'tasks.view.gantt.desc': 'Visualiza la duración, dependencias y progreso de las tareas.',
        'tasks.view.kanban.desc': 'Organiza tareas por estado: Pendiente, En Proceso y Completado.',
        'tasks.view.milestone.desc': 'Da seguimiento a entregas críticas y momentos importantes.',
        'tasks.view.tracking.desc': 'Consulta el tiempo invertido por tarea y responsable.',
        'tasks.tracking.upcomingActivity': 'Actividad Próxima',
        'tasks.tracking.upcomingSchedule': 'Agenda Próxima',
        'tasks.tracking.seeAll': 'Ver Toda la Actividad',
        'tasks.tracking.workingOn': 'En Progreso',
        'tasks.days.mon': 'Lun',
        'tasks.days.tue': 'Mar',
        'tasks.days.wed': 'Mié',
        'tasks.days.thu': 'Jue',
        'tasks.days.fri': 'Vie',
        'tasks.days.sat': 'Sáb',
        'tasks.days.sun': 'Dom',
        'tasks.field.assignee': 'Responsable',
        'tasks.field.duration': 'Duración',
        'tasks.field.start': 'Inicio',
        'tasks.field.end': 'Fin',
        'tasks.field.progress': 'Progreso',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('es');

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['en']] ||
            translations['en'][key as keyof typeof translations['en']] ||
            key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
